languageCode = "en"
languageName = "English"
weight = 1

title = "halme.org"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
  name = "Josiah Halme"
  image = "img/blowfish_logo.png"
  links = [
     { email = "mailto:hello@halme.org" },
     { facebook = "https://www.facebook.com/josiahhalme" },
     { github = "https://github.com/josiahhalme" },
     { linkedin = "https://linkedin.com/in/josiahhalme/" },
  ]
